import {
  Headphones,
  BarChart,
  Megaphone,
  Wallet,
  Gamepad,
  Truck,
  Monitor,
  Building2,
} from "lucide-react";

export const jobCategories = [
  {
    categoryId: 1,
    icon: Headphones,
    name: "Design",
    count: 200,
    color: "bg-orange-50",
    iconColor: "text-orange-500",
  },
  {
    categoryId: 2,
    icon: BarChart,
    name: "Sales",
    count: 350,
    color: "bg-purple-50",
    iconColor: "text-purple-600",
  },
  {
    categoryId: 3,
    icon: Megaphone,
    name: "Marketing",
    count: 500,
    color: "bg-red-50",
    iconColor: "text-red-500",
  },
  {
    categoryId: 4,
    icon: Wallet,
    name: "Finance",
    count: 200,
    color: "bg-yellow-50",
    iconColor: "text-yellow-600",
  },
  {
    categoryId: 5,
    icon: Gamepad,
    name: "Automobile",
    count: 250,
    color: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    categoryId: 6,
    icon: Truck,
    name: "Logistics/Delivery",
    count: 150,
    color: "bg-green-50",
    iconColor: "text-green-600",
  },
  {
    categoryId: 7,
    icon: Monitor,
    name: "Admin",
    count: 100,
    color: "bg-indigo-50",
    iconColor: "text-indigo-600",
  },
  {
    categoryId: 8,
    icon: Building2,
    name: "Construction",
    count: 500,
    color: "bg-cyan-50",
    iconColor: "text-cyan-600",
  },
];
